### ISSUE TITLE
Cannot import name 'Client'

### ISSUE THREAD

**Issue by AbhayAysola** [DarkCat09/python-aternos#1]
It seems as though Client is not a member of the module. I get an error when I try to run the code.

**Comment by DarkCat09** [comment]
Hello.  
I have never made Python-modules, so there are some problems in this API.  
`python-aternos` works from the version 0.2, but I forgot to edit Readme.  
Try to import it using the code below:
```python
from python_aternos import client
aternos = client.Client()
```
Thank you for your feedback!  
I think, I need to move the client class to `__init__.py`.

**Comment by AbhayAysola** [comment]
So I tried this, but I get another error ```    from atserver import AternosServer
ModuleNotFoundError: No module named 'atserver'```.

Thanks for the response.

**Comment by DarkCat09** [comment]
Try to update the module. It was fixed in v.0.2.

**Comment by AbhayAysola** [comment]
Yeah, it worked now. Thanks
