### ISSUE TITLE
Library installation error

### ISSUE THREAD

**Issue by R4mBLeR** [DarkCat09/python-aternos#10]
I used pip install python-aternos, but instead of successfully installing, I get this error:
```  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\avance\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of lxml
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml-4.8.0.dist-info\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml-4.8.0.dist-info
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Users\avance>
```

**Comment by DarkCat09** [comment]
Try to execute `pip install lxml`

**Comment by R4mBLeR** [comment]
> Попробуйте выполнить`pip install lxml`

2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\avance\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of lxml
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml-4.8.0.dist-info\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml-4.8.0.dist-info
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

Im trying

**Comment by DarkCat09** [comment]
OK, I know this problem. You should install a prebuilt package from https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml  
Choose `lxml-4.8.0-cp<PYTHON>-<ARCH(32bit/64bit)>.whl`
***
Ага, я знаю о проблеме. Вам надо поставить готовый (собранный) пакет с сайта выше.  
Выбирайте `lxml-4.8.0-cp<ВЕРСИЯ_PYTHON>-<БИТНОСТЬ_ПРОЦЕССОРА>.whl`

**Comment by R4mBLeR** [comment]
How to install this?

**Comment by DarkCat09** [comment]
Download file, then `pip install <path/to/the/package.whl>`

**Comment by R4mBLeR** [comment]
> Download file, then `pip install <path/to/the/package.whl>`

Я так сделал, но при попытки установки python-aternos удаляет его и опять скачивает

**Comment by R4mBLeR** [comment]
Всё равно эта ошибка    
   xmlXPathInit39eg_5fl.c
      C:\Users\avance\AppData\Local\Temp\xmlXPathInit39eg_5fl.c(1): fatal error C1083: ЌҐ г¤ Ґвбп ®вЄалвм д ©« ўЄ«озҐ­ЁҐ: libxml/xpath.h: No such file or directory,
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\avance\appdata\local\programs\python\python310\lib\site-packages
  Rolling back uninstall of lxml
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml-4.8.0.dist-info\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml-4.8.0.dist-info
  Moving to c:\users\avance\appdata\local\programs\python\python310\lib\site-packages\lxml\
   from C:\Users\avance\AppData\Local\Programs\Python\Python310\Lib\site-packages\~xml
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by DarkCat09** [comment]
Понял, значит надо ставить python-aternos без зависимостей (т.е. без автоматической установки нужных модулей).  
Вроде так: `pip install --no-deps python-aternos`  
Если каких-то зависимостей не хватает, установите вручную.

***

Now I understand. You should install python-aternos without dependencies (without auto-installing needed modulea).
If I don't mistake: `pip install --no-deps python-aternos`
If some deps are missing, install they manually.
