### ISSUE TITLE
Account Suspended

### ISSUE THREAD

**Issue by AmaaelTyrneaMitore** [DarkCat09/python-aternos#16]
My aternos account suspended by using it. Is there a way to prevent my accounts from getting banned.

![IMG_20220506_105617.jpg](https://user-images.githubusercontent.com/96770927/167072355-c2c06d74-5e67-4d65-a81b-6e99be325f67.jpg)

**Comment by sleeyax** [comment]
I'm not a contributor to this project, but I'm just here say that python's http/TLS stack is very easy to detect, making the problem very difficult to fix on a fundamental level if they perform that kind of detection.

**Comment by DarkCat09** [comment]
@AmaaelTyrneaMitore, you should use `save_session` and `Client.restore_session` to avoid detecting the automated access by detecting too many login requests.

@sleeyax, thanks, that's interesting. Can I do something? Like using selenium instead of requests.

**Comment by AmaaelTyrneaMitore** [comment]
You see, I python is not my forté so can you please (pretty please) provide me a snippet to turn on/off the server. Please😅

**Comment by DarkCat09** [comment]
```python
from getpass import getpass
from python_aternos import Client

try:
    aternos = Client.restore_session()
except Exception:
    user = input('Username: ')
    pswd = getpass('Password: ')
    aternos = Client.from_credentials(user, pswd)

server = aternos.list_servers()[0]
server.start()

aternos.save_session()
```

**Comment by sleeyax** [comment]
> @AmaaelTyrneaMitore, you should use `save_session` and `Client.restore_session` to avoid detecting the automated access by detecting many login requests.
> 
> @sleeyax, thanks, that's interesting. Can I do something? Like using selenium instead of requests.

You could look into puppeteer and puppeteer-stealth, though obviously that would be slower than plain HTTP requests . Honestly the easiest way is to just not use python and go lower level like go or rust but I suppose that's no option... Maybe there's better http packages than python requests though I'm not sure.

Here's my implementation in go (sorry for the self-advertisement): https://github.com/sleeyax/aternos-api/

**Comment by AmaaelTyrneaMitore** [comment]
@sleeyax I see that you also provided a binary to make things easy, but just make sure, am I supposed to do some additional configuration in order to prevent my account from getting banned?

**Comment by AmaaelTyrneaMitore** [comment]
BTW thanks @DarkCat09 for the help! I appreciate it!

**Comment by AmaaelTyrneaMitore** [comment]
I think since it's working now I am going to close the issue and again everyone thanks for your precious time💝

**Comment by sleeyax** [comment]
> @sleeyax I see that you also provided a binary to make things easy, but just make sure, am I supposed to do some additional configuration in order to prevent my account from getting banned?

Should work out of the box, though I can't **guarantee** your account won't ever get banned because there's plenty of factors that play a role (source IP, programmatic errors I overlooked, sudden increased protection, etc). No library author can guarantee it 100% though I haven't heard a complaint from consumers of my library this far.

If you have any more questions or need support, open an issue/discussion on the repo. I don't wanna clutter this issue with off-topic talk any further 😅
