### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by IronLung127** [DarkCat09/python-aternos#2]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    myserv = atservers[0]
IndexError: list index out of range

whenever i try to use this it always does this

main.py:

from python_aternos import Client 

aternos = Client('testyname1', password='***')
atservers = aternos.get_servers()

print(atservers)

myserv = atservers[0]

print(atservers)

myserv.start()
myserv.stop()

# Find server by IPx

testserv = None
for serv in atservers:
    if serv.address == 'testyname1.aternos.me':
        testserv = serv
if testserv != None:
    # Prints a server softaware and its version
    # (for example, "Vanilla 1.12.2")
    print(testserv.software, testserv.version)
    # Starts server
    testserv.start()

**Comment by DarkCat09** [comment]
Hello. Send, please, `print(atservers)` output.
