### ISSUE TITLE
How do I write something to the console?

### ISSUE THREAD

**Issue by Ivan228-s** [DarkCat09/python-aternos#20]
I really need to write commands to the console through the code, how is it possible to implement this?

**Comment by DarkCat09** [comment]
Можете по-русски объяснить? Гуглопереводчик теряет смысл фраз.

**Comment by Ivan228-s** [comment]
А, окей, крч, как можно написать команду в консоль? Очень надо

**Comment by Ivan228-s** [comment]
Если на данный момент такой возможности нет, можно такое сделать?

**Comment by DarkCat09** [comment]
Вы о чём-то типа этого?```
Command> login
Username: ...
Password:
Success
Command> listsrv
Server 1: test.aternos.me
Command> select 1
Sever 1
Command> start
Command> stop
```

**Comment by DarkCat09** [comment]
Или вызов из терминала / командной строки через `aternos start 1`?

**Comment by DarkCat09** [comment]
Сейчас такое не реализовано, это всего лишь модуль для разработки ботов или таких же CLI.  
Но сама идея была, её реализую я или @nm17

**Comment by Ivan228-s** [comment]
Хорошо, если что я про консоль из атерноса, в которой можно писать комманды
![Screenshot_2022-05-17-14-43-54-985_com android chrome](https://user-images.githubusercontent.com/72879188/168803401-fca5b030-3025-4f14-aff4-de742de5812f.jpg)

**Comment by Ivan228-s** [comment]
Просто очень срочно сейчас нужна данная функция, вот я её и ищу, как будет готово напишите

**Comment by DarkCat09** [comment]
А, понял. Сейчас так можно.

**Comment by DarkCat09** [comment]
Просто нормальную документацию у меня нет времени писать (к сожалению). Сейчас кину пример.

**Comment by Ivan228-s** [comment]
Хорошо, спасибо, я вас жду :>

**Comment by DarkCat09** [comment]
https://github.com/DarkCat09/python-aternos/blob/main/examples/console_example.py

**Comment by Ivan228-s** [comment]
Спс
