### ISSUE TITLE
add to server allow list

### ISSUE THREAD

**Issue by KarsonTheFoxx** [DarkCat09/python-aternos#26]
is it possible to do this?

**Comment by DarkCat09** [comment]
What did you mean?

**Comment by KarsonTheFoxx** [comment]
is it possible to add usernames to the allowlist or do i still need to go to aternos to do this? as in is there something like allowlist.add("username")

**Comment by DarkCat09** [comment]
Thanks, now I understand. It's possible.
```python
from python_aternos import Client, atplayers

at = Client.from_credentials('username', 'password')
serv = at.list_servers()[0]

# whl is whitelist
whitelist = serv.players(atplayers.Lists.whl)
print(whitelist.list_players()) #show all
whitelist.add('jeb_') #append
whitelist.remove('Notch') #remove
```

**Comment by KarsonTheFoxx** [comment]
awesome, could you respond to my other issue? i cant even get a list of my servers suddenly

**Comment by KarsonTheFoxx** [comment]
this doesnt work

**Comment by KarsonTheFoxx** [comment]
ive copied it exactly and its not adding it

**Comment by DarkCat09** [comment]
Answered in #30  
Please, enable logging.
