### ISSUE TITLE
when aternos account is in more than 5 servers list_servers() returns empty list

### ISSUE THREAD

**Issue by KarsonTheFoxx** [DarkCat09/python-aternos#29]
i deleted a few servers from the accounts list and my previous issue was resolved, it appears that theres an unlisted max number that it can have before it stops working.

**Comment by DarkCat09** [comment]
Thank you so much for the provided information.  
I'll check your servers HTML code today and answer here.  
5-servers limit is very strange.

**Comment by DarkCat09** [comment]
And also, could you enable logging as I said in #30 ? Just add to the beginning:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by KarsonTheFoxx** [comment]
yup
