### ISSUE TITLE
Can i just clone the git and move the contents into my /usr/local/python3.9/ folder?

### ISSUE THREAD

**Issue by KarsonTheFoxx** [DarkCat09/python-aternos#40]
`python3 -m pip install python-aternos`

didnt work because i was getting `FileNotFound` in the module metadata's setup.py

so is there a way i can manually add these file to my raspberry pi? (im using the 32 bit Raspberry pi OS based of buster 10)

**Comment by DarkCat09** [comment]
```bash
pip uninstall python-aternos
git clone https://codeberg.org/DarkCat09/python-aternos.git
cd python-aternos
sudo pip install -e .
```

**Comment by DarkCat09** [comment]
When new version with bugfixes will be released, you should install module from pip to receive updates easier.
```bash
# Reinstall
sudo pip uninstall python-aternos
pip install -U python-aternos

# Remove cloned git repo
rm -rf ~/python-aternos
```
