### ISSUE TITLE
Access servers that aren't yours like if someone gave you access to the server

### ISSUE THREAD

**Issue by BluePlattypus** [DarkCat09/python-aternos#47]
title

**Comment by DarkCat09** [comment]
Could you describe it more detailed? I don't know English very well to fully understand the title.

**Comment by didotb** [comment]
> title

You can already do this, as long as the server was shared to you with proper share privileges.

**Comment by DarkCat09** [comment]
@BluePlattypus, servers to which you have access appear in `list_servers()`.
