### ISSUE TITLE
PyPI Release isn´t upload

### ISSUE THREAD

**Issue by marlonedusc** [DarkCat09/python-aternos#6]
they still do not release the new client update to pypi repository

**Comment by marlonedusc** [comment]
I think I know why this happens, the connection cannot be generated yet, the "self.token" function returns True and not a text with the token, which prevents access and reading of "ATERNOS_SESSION"

**Comment by DarkCat09** [comment]
Done. Please, upgrade the module. ```bash
pip install --upgrade python-aternos
```

**Comment by marlonedusc** [comment]
WORKS! THANK YOU!!!
