### ISSUE TITLE
Add countdown function

### ISSUE THREAD

**Issue by ShaqimaK** [DarkCat09/python-aternos#60]
as the title
in https://aternos.org/panel/ajax/status.php

**Comment by DarkCat09** [comment]
OK, I'll add a property to AternosServer class.  
To update countdown in real-time, you still need to use Websocket API.

**Comment by DarkCat09** [comment]
Done (https://github.com/DarkCat09/python-aternos/commit/413fabb1a9d957260c6fcfc357ea7c078e9c6717)
