### ISSUE TITLE
do I need to buy cloudscraper premium version?

### ISSUE THREAD

**Issue by BishoyHanyRaafat** [DarkCat09/python-aternos#61]
That happen when I tried to login
aternos = Client.from_credentials('username', 'pass')

cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Comment by DarkCat09** [comment]
Hello.

Cloudscraper can't solve captcha, so you need a paid service to do it automatically.  
Please, read https://github.com/DarkCat09/python-aternos/issues/52#issuecomment-1268632758

The error message about "pro" version looks like a joke. Cloudscraper is open source.

**Comment by DarkCat09** [comment]
If I find a free solution for this, I'll write a comment in #52 issue.
