### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by DusanMarkovic12** [DarkCat09/python-aternos#64]
i tried to install a mod for my aternos server and it asked me to install other versions of the mods and i installed them but the enchdesc mod doesn't exist on aternos

**Comment by DusanMarkovic12** [comment]
For mod Enchencments

**Comment by DarkCat09** [comment]
Hello.  
My module is unofficial and is not related to Aternos GmbH.  
You should suggest the "enchdesc" mod to the Aternos developers:  
![Screenshot_20230107-182050](https://user-images.githubusercontent.com/50486086/211155571-aa8e22dd-8115-4f8d-9b41-017ccfc185f0.png)

**Comment by DarkCat09** [comment]
Also, check if you didn't misspell mod's name.
