### ISSUE TITLE
Passing commands to the console

### ISSUE THREAD

**Issue by reka7490** [DarkCat09/python-aternos#65]
EN: Hi, I have a question is it possible to enter commands into the server console somehow?
RU: И снова привет у меня есть вопросик а можно ли как то вводить команды в консоль сервера?

**Comment by DarkCat09** [comment]
Duplicate of #20

**Comment by DarkCat09** [comment]
Here is an example how to read and write to the server's console: https://github.com/DarkCat09/python-aternos/blob/main/examples/console_example.py  
You have to use Websockets API. And rememeber to start the server before working with console.

**Comment by DarkCat09** [comment]
По-русски:

Вот пример, как читать/записывать в консоль: https://github.com/DarkCat09/python-aternos/blob/main/examples/console_example.py  
Это делается через Websockets API. И не забудьте запустить сервер перед тем, как отсылать запросы к консоли.

**Comment by DarkCat09** [comment]
I hope I've answered the question.  
Надеюсь, ответил на вопрос.

**Comment by reka7490** [comment]
EN: not completely, but is it possible to do plug and play? (it is inconvenient to turn off and turn on the server so that commands go to the console)
RU: так может я глупый но консоль работает только если сервер включен через неё но можно ли как то обойтись без перезапуска и просто подключиться к консоли?

**Comment by DarkCat09** [comment]
@reka7490,

Да, команды можно отправлять только когда сервер запущен.  
Использование `wss.send()` на остановленном сервере ничего не даст.

Yes, commands can be sent only when server is running.  
Using `wss.send()` when server is stopped doesn't give any effect.

**Comment by reka7490** [comment]
EN: ...uh Okay I'll just show you what I mean
RU: ладно я просто покажу что имелось в виду
![image](https://user-images.githubusercontent.com/111941389/211300073-cbf52eba-d4f9-4f58-84b3-a6d36d5045e5.png)

**Comment by reka7490** [comment]
да блин ладно просто на русском объясню короче в файле примере есть запуск сервера s.start() я его удалил вручную запустил сервер (полностью) потом запустил файл пример но консоль не заработала могу кинуть скрин кода если нужно

**Comment by DarkCat09** [comment]
1 more question. Which version of python-aternos do you have?  
Ещё вопрос: какая у Вас версия модуля?

**Comment by reka7490** [comment]
![image](https://user-images.githubusercontent.com/111941389/211732563-a109c8f0-ab39-40c3-8e76-397e89882130.png)

**Comment by reka7490** [comment]
![image](https://user-images.githubusercontent.com/111941389/211737403-c8938b27-1a4c-40ec-ba0a-f70a46261af5.png)
EN: okay I updated all the modules using pip and checked the error again the error remained
RU: я обновил все модули но ничего не изменилось

**Comment by DarkCat09** [comment]
@reka7490,

У меня всё работает.  
Вы нажали Y когда скрипт спросил "Show responses"?

It works for me.  
Did you press Y when the script asked "Show responses"?

**Comment by reka7490** [comment]
![image](https://user-images.githubusercontent.com/111941389/212342566-5c8064b3-148f-4200-b203-625707bc7f4e.png)
EN: no I replaced this part of the code
RU: у меня он залочен и да я знаю что у меня нет вкуса

**Comment by reka7490** [comment]
![image](https://user-images.githubusercontent.com/111941389/212344078-ded45a73-5b06-4dad-bcd3-6e9b65c27b55.png)
EN: here you can see everything is working if you run the server through the code, but if you first turn on the server yourself, wait for the load and only then start the console, then nothing will work
RU: вот тут видно всё рабит если сервер запускать через код но если сначала самому включить сервер дождаться загрузки и лишь потом запустить консоль то ничего не сработает

**Comment by reka7490** [comment]
шок контент чёрный кот стал коричневым 😱 ТАК ДЕРЖАТЬ

**Comment by DarkCat09** [comment]
> шок контент чёрный кот стал коричневым ТАК ДЕРЖАТЬ

Ага :)  
На предыдущей аватарке, правда, кот был примерно такого же цвета.  
А вообще, сообщения, не относящиеся к python-aternos, лучше в тг-канал, группу обсуждения или личный чат:
- https://t.me/dcat09
- https://t.me/darkcat09

**Comment by DarkCat09** [comment]
@reka7490,

Your last screenshots was moved to a new issue with title related to this bug. You can continue the discussion there: #68  
This one will be closed.

Последние скрины перенёс в новый issue, с соответствующим заголовком. Обсуждение самого бага можно продолжить тут: #68  
Этот issue закрою.
