### ISSUE TITLE
ModuleNotFoundError: No module named 'python_aternos'

### ISSUE THREAD

**Issue by rayorsomething** [DarkCat09/python-aternos#67]
I installed it with "pip install python-aternos", imported using "from python_aternos import Client" and ran it then got this error

**Comment by rayorsomething** [comment]
what info should i provide

**Comment by DarkCat09** [comment]
@rayorsomething,
Hello. Could you answer:  
- How did you install the module?
- What IDE do you use?
- What operating system do you use?

**Comment by rayorsomething** [comment]
like i said i installed it using "pip install python-aternos"
i use vscodium
im on windows

**Comment by DarkCat09** [comment]
> like i said i installed it using "pip install python-aternos" i use vscodium im on windows

Run `pip list` and paste all its output here, please.

**Comment by rayorsomething** [comment]
```
certifi               2022.12.7
charset-normalizer    3.0.1
cloudscraper          1.2.68
idna                  3.4
Js2Py                 0.74
lxml                  4.9.2
pip                   23.0
pyjsparser            2.7.1
pyparsing             3.0.9
python-aternos        2.1.3
pytz-deprecation-shim 0.1.0.post0
regex                 2022.10.31
requests              2.28.2
requests-toolbelt     0.10.1
six                   1.16.0
tzdata                2022.7
tzlocal               4.2
urllib3               1.26.14
websockets            10.4
```

**Comment by DarkCat09** [comment]
@rayorsomething, thanks a lot.  
The list looks correct. Try to run your code one more time.

**Comment by DarkCat09** [comment]
@rayorsomething,

Do you still have this problem?  
What if you reinstall python-aternos?

**Comment by TechDudie** [comment]
> I installed it with "pip install python-aternos", imported using "from python_aternos import Client" and ran it then got this error

I think that it's because you may have python 2.7 or something on your computer, try `pip3 install python-aternos` @rayorsomething

**Comment by DarkCat09** [comment]
Reopen the issue if needed
