### ISSUE TITLE
Aternos Confirmation

### ISSUE THREAD

**Issue by marlonedusc** [DarkCat09/python-aternos#7]
Now you have the same problem as AternosAPI, Aternos asks for confirmation to open the server, manual, I don't know how you could automate that, but I just let you know; D

**Comment by DarkCat09** [comment]
Thank you. I know about this problem, but I haven't any ideas how to fix this.
Maybe it will be implemented in the next version...

**Comment by DarkCat09** [comment]
Aternos checks the server state using websocket. This feature will be added in v.0.6, view https://github.com/DarkCat09/python-aternos/blob/main/aternos_ws.txt

**Comment by DarkCat09** [comment]
https://github.com/DarkCat09/python-aternos/blob/main/python_aternos/atwss.py#L107
