### ISSUE TITLE
partially initialized module 'inspect' has no attribute 'signature'

### ISSUE THREAD

**Issue by MedCodeMC** [DarkCat09/python-aternos#70]
Hello.
I'm trying to log in my account using python-aternos libary,
and i can't solve an error
This is my code:
```
from python_aternos import Client

aternos = Client.from_credentials('(My_Username', 'My_Password')
```

And this is the error:

![Capture d’écran 2023-03-10 220022](https://user-images.githubusercontent.com/127552346/224427362-56223341-174a-4f2e-9626-e03df01e5bea.png)

Can someone help me!

**Comment by DarkCat09** [comment]
@MedCodeMC, just rename your file to something else, `dis` is a special builtin module.  
`lxml` library requires dis, and tries to import it, but instead it imports your file.
