### ISSUE TITLE
CloudflakeChallengeError

### ISSUE THREAD

**Issue by LeeTuah** [DarkCat09/python-aternos#71]
This is the output on running the from_credentials() function in the Client class:

cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

**Comment by DarkCat09** [comment]
Duplicate of #52

**Comment by DarkCat09** [comment]
@LeeTuah, you need an API key on paid services like 2captcha for automatic captcha solving.  
See #52 for more information.
