### ISSUE TITLE
Code hang in using session

### ISSUE THREAD

**Issue by Supslike** [DarkCat09/python-aternos#81]
when I use username and password for logging in, starting the server works absolutely fine
```python
aternos = Client()
aternos.login(username = os.environ["username"]), password = os.environ["password"])
aternos_account = aternos.account
server = aternos_account.list_servers()[0]
server.start()
``` 

But when I use session for logging in, it gets stuck on server.start()
```python
aternos = Client()
aternos.login_with_session(session=os.environ["session"])
aternos_account = aternos.account
server = aternos_account.list_servers()[0]
server.start()
``` 

it doesn't only affect start but also stop, and restart

**Comment by DarkCat09** [comment]
Try to add these lines after `login_with_session`:
```python
aternos.parse_token()
aternos.generate_sec()
```

That was fixed in the last commit, but not released.

**Comment by Supslike** [comment]
I get this now

AttributeError: 'Client' object has no attribute 'parse_token'

**Comment by DarkCat09** [comment]
@Supslike, I'm sorry, I meant this code:
```python
aternos.atconn.parse_token()
aternos.atconn.generate_sec()
```
